---
analyses : ['2106.01676']
input_folder : '../data/'
output_folder : '../tables/'
processes : 1
scans : 1
points : 100
bkg_unc_samples : 500
low_lim_samples : 30
buffer_size : 100
start_method : 'random'
scan_criterion : 'mu1'
SR_sigma : 0.05
CR_sigma : 0.02
VR_sigma : 0.02
signal_leakage_CR : True
signal_leakage_CR_spread : 0.10
signal_leakage_CR_sign : 'both'
signal_leakage_VR : False
signal_leakage_VR_spread : 0.10
signal_leakage_VR_sign : 'both'
keep_files : False
fit_bkg : False
spey_verbose_lvl : 0
removeCRsVRs : False
cluster : True
---
analysis : '1909.09226'
include : cards/1909.09226.yaml
scans : 200
processes : 30
points : 500
low_lim_samples : 30
bkg_unc_samples : 2000
buffer_size : 100
---
analysis : '1911.06660'
include : cards/1911.06660.yaml
scans : 1
processes : 1
points : 30
low_lim_samples : 1
bkg_unc_samples : 10
signal_leakage_CR: False
removeCRsVRs : False
---
analysis : '1911.12606'
include : cards/1911.12606.yaml
scans : 1
processes : 1
points : 500
buffer_size : 20
low_lim_samples : 50
signal_leakage_CR_spread : 0.2
signal_leakage_VR_spread : 0.2
remove_channels :
  - SR_eMLLa_Onelep1track_cuts
  - SR_eMLLb_Onelep1track_cuts
  - SR_eMLLc_Onelep1track_cuts
  - SR_eMLLd_Onelep1track_cuts
  - SR_eMLLe_Onelep1track_cuts
  - SR_eMLLf_Onelep1track_cuts
cluster : True
---
analysis : '1908.08215'
include : cards/1908.08215.yaml
scans : 1
processes : 1
points : 1000
low_lim_samples : 50
buffer_size : 20
signal_leakage_CR_spread : 0.20
signal_leakage_VR_spread : 0.20
start_method : 'fine-tune'
cluster : True
CR_center : 'exp'
VR_center : 'exp'
SR_sigma' : 0.1
CR_sigma' : 0.001
VR_sigma' : 0.001
scan_criterion : 'nLL_exp_mu1'                                                                                                
---
analysis : '1912.08479'
include : cards/1912.08479.yaml
scans : 2
processes : 2
points : 100
buffer_size: 20
low_lim_samples : 3
---
analysis : '2106.01676'
include: cards/2106.01676.yaml
scan : 1
processes : 1
points : 500
buffer_size : 20
low_lim_samples : 60
signal_leakage_CR_spread : 0.20






