author: 'Rafal Maselek'
# base number of neurons in each layer
neurons: 4096
# how many blocks (block=dense+batch_norm+activation+dropout)
blocks: 5
# L2 regularisation
l2: 0.0001
# activateion: relu, relu6, tanh, elu, swish
activation: 'elu'
# use batch norm or not
batch_norm: True
# dropout rate
dropout_rate: 0.0
# use residual connections to all blocks
use_residual : False
# loss: MSE, M4E, MAE, MAPE, hybrid, huber, log_cosh, triple, MSLE
# see losses.py for definitions
loss : 'hybrid'
# train separate heads for each output
separate_heads : False
# number of neurons in a head
head_size : 512
# use batch norm in heads
head_batch_norm : True
# size of the gradient clipping
gradient_clipping : 1.0
# epochs to train
epochs: 10000
# random seed, leave it commented out for random
#seed: 0
batch_size: 1024
# optimizer: Adam, AdamW
optimizer: 'Adam'
early_stop: true
optimize: false



